### ISSUE TITLE
"containerd" under RockyLinux 9 fails because of SELinux

### ISSUE THREAD

**Issue by mnaser** [vexxhost/ansible-collection-containers#27]
https://ci.atmosphere.dev/t/atmosphere/build/3e64d174889744d4b096c9e7b1abf091

**Comment by mnaser** [comment]
@fitbeard I think we might need help from your side on this, we have native VMs for CI which can let us things more reliably (from #26 )

**Comment by fitbeard** [comment]
@mnaser SELinux is more aggressive on RHEL9. It's in enforced mode by default (before on EL7/8 mode was permissive). My proposal would be to set SELinux to permissive mode for CI and leave real configuration for users. Users will almost always turn this off:(

Just pass this in a first place before other steps: `sudo setenforce 0` or use real ansible:

```
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
```

or

```
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
```
